name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt install libfuse3-dev
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --no-deps
    - name: Run tests
      run: cargo test --verbose
