name: tests

on:
  push:
    branches: [ "main", "test-ci" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Build
      run: cargo build -v
    - name: Clippy
      run: cargo clippy --no-deps
    - name: Run tests
      run: |
        export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER='sudo -E'
        cargo test
